language: go

go: "1.13.x"

sudo: false

matrix:
  fast_finish: true

before_install:
  - echo 'Install deps here..'

script:
  - cd ./src
  - test -z "$(gofmt -l .)"
  - go build -ldflags='-s -w' -o /tmp/tinifier .
  - /tmp/tinifier -v
