language: go

go: "1.13.x"

addons:
  apt:
    packages:
      - upx

git:
  depth: 1

env:
  global:
    - LDFLAGS='-s -w'
    - UPX_PARAMS=-5

matrix:
  fast_finish: true

before_script: cd ./src

script:
  - test -z "$(gofmt -l .)"
  - go test . -v -race -coverprofile=coverage.txt -covermode=atomic
  - go build -ldflags="$LDFLAGS" -o /tmp/tinifier .
  - ls -lh /tmp/tinifier
  - /tmp/tinifier -V

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt

before_deploy:
  - mkdir /tmp/build
  - GOOS='linux' GOARCH='386' go build -ldflags="$LDFLAGS" -o /tmp/build/tinifier_386 ./main.go
  - GOOS='linux' GOARCH='amd64' go build -ldflags="$LDFLAGS" -o /tmp/build/tinifier_amd64 ./main.go
  - GOOS='windows' GOARCH='386' go build -ldflags="$LDFLAGS" -o /tmp/build/tinifier_386.exe ./main.go
  - GOOS='windows' GOARCH='amd64' go build -ldflags="$LDFLAGS" -o /tmp/build/tinifier_amd64.exe ./main.go
  - upx $UPX_PARAMS /tmp/build/*

deploy:
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file_glob: true
    file:
      - /tmp/build/*
    skip_cleanup: true
    on:
      tags: true
      branch: master
