language: go

go: "1.13.x"

sudo: false

cache:
  directories:
    - $HOME/gopath

matrix:
  fast_finish: true

before_script: cd ./src

script:
  - test -z "$(gofmt -l .)"
  - go test . -v -coverprofile=coverage.txt -covermode=atomic
  - go build -ldflags='-s -w' -o /tmp/tinifier .
  - ls -lh /tmp/tinifier
  - /tmp/tinifier -V

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt
